version: "3.9"
services:
  owncast:
    image: gabekangas/owncast
    container_name: "owncast"
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
      - "1935:1935"
    volumes:
      - "./data:/app/data"
    extra_hosts:
      - host.docker.internal:host-gateway