services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ../certificates:/etc/letsencrypt
      - ../nginx/html:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"