services:
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:latest
    container_name: bluemap
    hostname: bluemap
    restart: always
    command: -r -u -w
    ports:
      - '8100:8100'
    volumes:
      - '../minecraft/mohist/world:/app/world'
      - '../minecraft/mohist/world_nether:/world_nether'
      - '../minecraft/mohist/world_the_end:/world_the_end'
      - './data/config:/app/config'
      - './data:/app/data'
      - './data/web:/app/web'
    extra_hosts:
      - 'host.docker.internal:host-gateway'