version: '3.1'
services:
  coredns:
    image: coredns/coredns:1.9.4
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coredns
    network_mode: host
    volumes:
      - './config/Corefile:/etc/coredns/Corefile'
      - './config/hosts:/etc/coredns/hosts'