version: '3.9'
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.23.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Tokyo
    restart: always