version: '3.9'
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.25.3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ../certificates/live:/certificates/live:ro
      - ../certificates/self-signed:/certificates/self-signed:ro
      - ./html:/var/www/html
      - ../nextcloud/html:/var/www/nextcloud
    environment:
      TZ: Asia/Tokyo
    restart: always
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    command: "/bin/sh -c 'while :; do sleep 36h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"