version: '3.9'
services:
  mackerel-agent:
    image: mackerel/mackerel-agent
    container_name: mackerel-agent
    hostname: coffee
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/lib/mackerel-agent
      - ./conf.d:/etc/mackerel-agent/conf.d:ro
    env_file:
      - .env
    environment:
      - enable_docker_plugin=1
      - auto_retirement=0
      - include=/etc/mackerel-agent/conf.d/*.conf
    restart: always
    networks:
      - minecraft_default

networks:
  minecraft_default:
    external: true
