x-logging: &logging
  driver: json-file
  options:
    max-file: "1"
    max-size: 10m

version: "3.7"
services:
  mirakurun:
    build: ./mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    env_file:
      - .env
    ports:
      - 40772:40772
      - 9229:9229
    devices:
      - /dev/bus:/dev/bus
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
    volumes:
      - ./mirakurun/config:/app-config/
      - ./mirakurun/data/:/app-data/
      - mirakurun_socket:/var/run
    restart: always
    logging: *logging

  epgstation:
    build: 
      context: ./epgstation
      dockerfile: debian.Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./epgstation/config:/app/config
      - ./epgstation/data:/app/data
      - ./epgstation/thumbnail:/app/thumbnail
      - ./epgstation/logs:/app/logs
      - /mnt/storage1/TV/Record:/app/recorded
      - /dev/dri:/dev/dri
      - mirakurun_socket:/var/run
    devices:
      - /dev/dri/card0:/dev/dri/card0
    # privileged: true
    user: 0:0
    depends_on:
      - mirakurun
      - db
    ports:
      - 8888:8888
      - 8889:8889
    restart: always
    logging: *logging
  
  konomitv:
    image: konomitv
    container_name: konomitv
    build:
      context: ./konomitv
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    volumes:
      - type: bind
        source: './konomitv/config.yaml'
        target: '/code/config.yaml'
      - type: bind
        source: './konomitv/server/data/'
        target: '/code/server/data/'
      - type: bind
        source: './konomitv/server/logs/'
        target: '/code/server/logs/'
      - type: bind
        source: '/'
        target: '/host-rootfs/'
    devices:
      - '/dev/dri/:/dev/dri/'
    depends_on:
      - mirakurun

  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
    restart: always
    logging: *logging
    
volumes:
  mirakurun_socket:
