version: '3.9'
services:
  minecraft:
    container_name: minecraft
    hostname: minecraft
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./waterfall:/app/waterfall
      - ./paper:/app/paper
      - /mnt/storage1:/mnt/storage1
      - /mnt/storage2:/mnt/storage2
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      WATERFALL_JAVA_OPTS: "-Xms1024M -Xmx2048M"
      PAPER_JAVA_OPTS: "-Xms4096M -Xmx8192M"
    ports:
      - 25565:25565/tcp