version: '3.9'
services:
  minecraft:
    container_name: minecraft
    hostname: minecraft
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./waterfall:/app/waterfall
      - ./paper:/app/paper
      - /mnt/storage1:/mnt/storage1
      - /mnt/storage2:/mnt/storage2
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      WATERFALL_JAVA_OPTS: "-Xms1024M -Xmx2048M"
      PAPER_JAVA_OPTS: "-Xms4096M -Xmx8192M"
    ports:
      - 25565:25565/tcp
    networks:
      - minecraft_default
      - internal
    depends_on:
      - db
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:latest
    container_name: bluemap
    hostname: bluemap
    restart: always
    command: -r -u -w
    ports:
      - '8100:8100'
    volumes:
      - './paper/world:/app/world'
      - './paper/world_nether:/world_nether'
      - './paper/world_the_end:/world_the_end'
      - './bluemap/config:/app/config'
      - './bluemap:/app/data'
      - './bluemap/web:/app/web'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  db:
    restart: unless-stopped
    image: mariadb:10.7.3-focal
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/log:/var/log/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
        TZ: 'Asia/Tokyo'
        MYSQL_ROOT_PASSWORD: 'root'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    networks:
      - internal

networks:
  minecraft_default:
    external: true
  bluemap_default:
    external: true
  internal: