version: '3.9'
services:
  minecraft:
    container_name: minecraft
    hostname: minecraft
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mohist:/app/mohist
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      JAVA_OPTS: "-Xms4096M -Xmx8192M"
    ports:
      - 25565:25565/tcp
    networks:
      - internal
    depends_on:
      - db
  backup:
    container_name: backup
    hostname: backup
    user: root
    build:
      context: ./backup
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mohist/world:/app/world
      - ./mohist/world_nether:/app/world_nether
      - ./mohist/world_the_end:/app/world_the_end
      - /mnt/storage1:/mnt/storage1
      - /mnt/storage2:/mnt/storage2
    environment:
      TZ: "Asia/Tokyo"
  db:
    container_name: db
    hostname: db
    restart: unless-stopped
    image: mariadb:10.7.3-focal
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/log:/var/log/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
        TZ: 'Asia/Tokyo'
        MYSQL_ROOT_PASSWORD: 'root'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    networks:
      - internal

networks:
  internal: