version: '3.9'
services:
  paper:
    container_name: paper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./paper:/app
    tty: true
    stdin_open: true
    environment:
      JAVA_OPTS: "-Xms4096M -Xmx8192M"
    ports:
      - 25565:25565/tcp