version: '3.9'
services:
  minecraft:
    container_name: minecraft
    hostname: minecraft
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      JAVA_OPTS: "-Xms4096M -Xmx8192M"
    ports:
      - 25565:25565/tcp